server:
  servlet:
    context-path: /novopay/v1/
spring:
  datasource:
    driverclassname: org.h2.Driver
    url: jdbc:h2:mem:testdb;mode=oracle
    username: test
    password:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        use_sql_comments: false
        format_sql: false
        jdbc:
          batch_size: 200
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create-drop